### ISSUE TITLE
get library config from .cproject

### ISSUE THREAD

**Issue by woniulive** [elmot/clion-embedded-arm#105]
## Expected Behavior
After configuring library in sw4stm,clion can configure  library by reading .cproject.which means lines below can work:

![image](https://user-images.githubusercontent.com/11304897/41347506-7561a4f8-6f3c-11e8-91b4-96bfb50d0732.png)

## Steps to Reproduce the Problem

  1.configure library in sw4stm
  2.click update cmake project to ...
  3.library confuguration don't add to cmakelists.txt

**Comment by elmot** [comment]
-  Please specify stm32cubemx version (you can find it in help->about menu)
- Please share, if possible, your .ioc file

**Comment by woniulive** [comment]
@elmot it is added by sw4stm,not stm32cubemx.after exporting from stm32cubemx,import to sw4stm32,then it shows the code i uploaded.

**Comment by elmot** [comment]
Sorry, I am afraid it's not going to be implemented in any visible future.
