### ISSUE TITLE
Shipped gdb is not found

### ISSUE THREAD

**Issue by DenisKuzovin** [elmot/clion-embedded-arm#106]
Hello! 

When I try to start debugger I get this error:
Error running 'OCD test1': Shipped gdb is not found. Please check your CLion install

I think that this happened, because the path to bundled gdb in the clion installation is changed.

Path to gdb in 182.3458.13:
...\JetBrains\CLion 182.3458.13\bin\gdb\win\bin\gdb.exe

Old style path to gdb (in 2018.1.5 to examle):
...\JetBrains\CLion 2018.1.5\bin\gdb\bin\gdb.exe

  - Plugin Version: 1.1.alpha6
  - CLion version: 182.3458.13
  - Platform: Win10 x64

**Comment by elmot** [comment]
Workaround - explicitly set GDB location

**Comment by elmot** [comment]
Fixed with a41bdc29cf0575eb6469cc5f4e311c92dbdf38ff
