### ISSUE TITLE
How to use gprof

### ISSUE THREAD

**Issue by savent404** [elmot/clion-embedded-arm#114]
## Expected Behavior
I want to use gcc-gprof to analyze.

  - Toolchain:  arm-none-eabi-gcc

**Comment by elmot** [comment]
Useful link
https://mcuoneclipse.com/2015/08/23/tutorial-using-gnu-profiling-gprof-with-arm-cortex-m/

**Comment by elmot** [comment]
Moved to https://youtrack.jetbrains.com/issue/CPP-15809
