### ISSUE TITLE
OpenOCD support dialog incomplete. No way of specifying board

### ISSUE THREAD

**Issue by xerydf** [elmot/clion-embedded-arm#128]
## Expected Behavior
pressing Control + Alt + S
and choosing Build, Execution , Development -> openOCE Support
A dialog looking like shown in the blog. ie. something like this:
![image](https://user-images.githubusercontent.com/44416872/47396117-dd3a0c00-d729-11e8-8b04-e65eb07ec49d.png)

is expected to apear

## Actual Behavior

Instead the dialog looks like the:

![openocd](https://user-images.githubusercontent.com/44416872/47396026-7e749280-d729-11e8-987a-2ef22cd9a578.jpg)

## Steps to Reproduce the Problem
As described above or 
Trying to flash and debug the build binary by
  1. Press Shif-F9
The this box pops up:
![image](https://user-images.githubusercontent.com/44416872/47396304-779a4f80-d72a-11e8-8a79-94809f3bf5c5.png)

  2. Clicking Settings button, I'm returned to the dialog w. missing input fields for board coanfig etcc.
![image](https://user-images.githubusercontent.com/44416872/47396389-c516bc80-d72a-11e8-9a38-9baec1817410.png)
  

## Specifications

  - Plugin Version:
1.1alpha7
![image](https://user-images.githubusercontent.com/44416872/47396546-8df4db00-d72b-11e8-8843-a4ce5ae88243.png)

  - CLion version:
2018.2.5
![image](https://user-images.githubusercontent.com/44416872/47396168-035fac00-d72a-11e8-9803-fb214c211a0d.png)

  - OpenOCD version:
0.10.0

  - GDB Version:
Clion buldled version: 8.1

  - STM32CubeMX version:
![image](https://user-images.githubusercontent.com/44416872/47396592-c5638780-d72b-11e8-8b18-b0306c9cf24f.png)

  - Toolchain:
arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2017-q4-major) 7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204]

- MinGW:
5.0
![image](https://user-images.githubusercontent.com/44416872/47396677-18d5d580-d72c-11e8-8f3b-991640085eca.png)

It's an unofficial build downloaded via link from th eopenOCD page. I followed the suggestion sposted on the blog januarey 9th by Max copying the scripts from openOCD_home to openOCCD_home/scare/scripts. this didn't make any difference.

  - Platform:
win10 Pro 1803 - 64Bit

  - Hardware configuration:
i3-4360 @ 3.7GHz & 8GB RAM

![image](https://user-images.githubusercontent.com/44416872/47396621-e035fc00-d72b-11e8-8a57-dd40569cbb73.png)

**Comment by xerydf** [comment]
I didn't specify the board. It's a STM32F4Discovery

**Comment by elmot** [comment]
The plugin was advanced a little big since that blog post. Now all those settings are in `Run/Debug  Configuration` dialog.
