### ISSUE TITLE
Wrong objcopy executed.

### ISSUE THREAD

**Issue by kbuc** [elmot/clion-embedded-arm#133]
## Expected Behavior
Building project should succeed.

## Actual Behavior
Fails due to MinGW's objcopy being executed. Error says objcopy does not recognise elf file.

## Steps to Reproduce the Problem

  1. don't put toolchain in path
  2. set full paths in CMakeLists.txt executables
  3. compile the project

## Specification
 * Windows 7
 * Plugin Version: 1.2.alpha3
 * CLion version: 2018.3.1
 * Toolchain: GNU gdb (GNU Tools for Arm Embedded Processors 7-2018-q2, gcc-arm-none-eabi-7-2018-q2) 

## Comments
Not sure if this is actually a bug or just my misconfiguration (due to toolchain not being in path), but 
my solution is to change CMakeLists.txt template from:

```
        COMMAND $${CMAKE_OBJCOPY} -Oihex $<TARGET_FILE:$${PROJECT_NAME}.elf> $${HEX_FILE}
        COMMAND $${CMAKE_OBJCOPY} -Obinary $<TARGET_FILE:$${PROJECT_NAME}.elf> $${BIN_FILE}
````
to 
```
        COMMAND $${OBJCOPY} -Oihex $<TARGET_FILE:$${PROJECT_NAME}.elf> $${HEX_FILE}
        COMMAND $${OBJCOPY} -Obinary $<TARGET_FILE:$${PROJECT_NAME}.elf> $${BIN_FILE}
```

After that, a proper objcopy is called and building the project is successful.

**Comment by elmot** [comment]
Should be fixed when https://youtrack.jetbrains.com/issue/CPP-871 is done
