### ISSUE TITLE
Set board config file from CMake

### ISSUE THREAD

**Issue by lesto** [elmot/clion-embedded-arm#137]
would be possible to determine what board file to use by setting a variable containing the path from CMAKE?

**Comment by elmot** [comment]
Can you clarify a little bit? With the example, probably

**Comment by lesto** [comment]
I have a CMAKE where you can select different chip; the cmake will reload and select the correct library and compilation settings. The problem is the OpenOCD configuration will still point to the original "board file config file".
But actually i found a way around; i simply select a conf file in a generic folder, and override it with the conf required by the specific chip :)
