### ISSUE TITLE
Feature request: Pass user OpenOCD arguments

### ISSUE THREAD

**Issue by kiciek** [elmot/clion-embedded-arm#64]
Right now all controll user has over OpenOCD is selecting board script
1. Add freedom to chose more then one script (separate target and interface scripts)
2. Change OpenOCD commands from default `;reset;shutdown` to any.

AC6 System Workbench 4 STM32 has interface with many options
![sw4stm32_debugger](https://user-images.githubusercontent.com/19826877/34210974-f5965e5e-e597-11e7-861a-561d2b1ca4b5.png)
![sw4stm32_startup](https://user-images.githubusercontent.com/19826877/34210975-f5b12126-e597-11e7-9f10-0c1c2151fd71.png)

**Comment by elmot** [comment]
1. I decided not to do this. Feel free to write your own board config and place it, for instance, into your project - the syntax is pretty trivial. I think I need add that to the documentation.
2. Good point.

**Comment by mchodzikiewicz** [comment]
I am also very interested in those features.
I would like to point out, that 'board' approach is only valid as long as you use devkit with debugger onboard, when you use custom hardware, it would be preferred not to rewrite config each time I change my probe, since probe and target are separate devices.

**Comment by kiciek** [comment]
Sorry, but I cannot find it myself. How do I put verify in script to check if firmware was loaded without errors?

**Comment by elmot** [comment]
@mchodzikiewicz , you may use your on per-project board config file. Those files in most cases contain just two includes -for the probe and for the target.
