### ISSUE TITLE
Feature request: Move board selection to Run/Debug configuration

### ISSUE THREAD

**Issue by kiciek** [elmot/clion-embedded-arm#65]
Move `Board Config File` and any future OpenOCD configuration from `File->Settings->Build, Execution, Deployment->OpenOCD Support` to `Run/Debug Configurations->OpenOCD Download & Run` to allow fast switching between targets or interfaces or both.

**Comment by elmot** [comment]
Is that really helpful? The plugin config is specific to the project, i hardly can imagine what for that fast switch is done w

**Comment by kiciek** [comment]
It is useful to run with and without semihosting, or to debug running firmware without resetting target.
Sadly both configurations are saved in .idea/workspace.xml and because of that are not possible to share by version control.

**Comment by makkarpov** [comment]
It's also useful when you have to debug multiple boards at once, so you can have different board scripts to select individual boards.

+1 for feature
