### ISSUE TITLE
Make sure `waitFor` is never called on UI thread

### ISSUE THREAD

**Issue by amakeev** [elmot/clion-embedded-arm#7]
https://github.com/elmot/cubemx-clion/blob/ac7a2377e889ddb805a841b4a141e7354d9c832c/src/xyz/elmot/clion/openocd/OpenOcdRun.java#L54

**Comment by elmot** [comment]
How can I delay debugger start for a while?

**Comment by amakeev** [comment]
Since  `OpenOcdLauncher` needs to stop the current process in `createProcess`, you have 2 options:
1) Show a progress dialog to let the user know that IDE is waiting for something, with 'Cancel' button.
(`com.intellij.openapi.progress.ProgressManager#runProcessWithProgressSynchronously`)
2) Create your own `ProcessHandler` that will make sure only one backing `Ocd` process is present, doing this in background (more complicated).
