### ISSUE TITLE
not in execute format: File Format not recognized when running debug

### ISSUE THREAD

**Issue by mintisan** [elmot/clion-embedded-arm#70]
## Expected Behavior

Debug normally.

## Actual Behavior

Shows `Firmware Download Success`, but `File Format not recognized` as below:
![image](https://user-images.githubusercontent.com/9136049/34492088-10c82d0e-f021-11e7-8bf6-d732f4dfd51a.png)

And my gdb and openocd seems fine as below:

```
➜  openocd-bin-0.10.0-MacOS file /usr/local/bin/arm-none-eabi-gdb
/usr/local/bin/arm-none-eabi-gdb: Mach-O 64-bit executable x86_64
➜  openocd-bin-0.10.0-MacOS file local/bin/openocd
local/bin/openocd: Mach-O 64-bit executable x86_64
```

`Run OpenOCD` result:
```
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 2000 kHz
adapter_nsrst_delay: 100
none separate
srst_only separate srst_nogate srst_open_drain connect_deassert_srst
Info : tcl server disabled
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : clock speed 1800 kHz
Info : STLINK v2 JTAG v22 API v2 SWIM v5 VID 0x0483 PID 0x374B
Info : using stlink api v2
Info : Target voltage: 3.266974
Info : stm32f4x.cpu: hardware has 6 breakpoints, 4 watchpoints
```

If I missed any settings ? 

My settings are as below:
![image](https://user-images.githubusercontent.com/9136049/34493284-217b37d6-f026-11e7-9f54-c869ac630d68.png)
![image](https://user-images.githubusercontent.com/9136049/34493290-2f7d6e94-f026-11e7-8c98-dff938446434.png)
![image](https://user-images.githubusercontent.com/9136049/34493299-39a29cf0-f026-11e7-8166-c0bff0f062f3.png)

![image](https://user-images.githubusercontent.com/9136049/34493203-c8ba46aa-f025-11e7-92b3-d5d87f99667f.png)

CMakeLists.txt
```
SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_VERSION 1)
cmake_minimum_required(VERSION 3.7)

# specify the cross compiler
SET(CMAKE_C_COMPILER_WORKS 1)
SET(CMAKE_C_COMPILER arm-none-eabi-gcc)
SET(CMAKE_CXX_COMPILER arm-none-eabi-g++)


SET(LINKER_SCRIPT ${CMAKE_SOURCE_DIR}/STM32F401RETx_FLASH.ld)

#Uncomment for hardware floating point
#SET(FPU_FLAGS "-mfloat-abi=hard -mfpu=fpv4-sp-d16")
#add_definitions(-DARM_MATH_CM4 -DARM_MATH_MATRIX_CHECK -DARM_MATH_ROUNDING -D__FPU_PRESENT=1 )

#Uncomment for software floating point
#SET(FPU_FLAGS "-mfloat-abi=soft")

SET(COMMON_FLAGS "-mcpu=cortex-m4 ${FPU_FLAGS} -mthumb -mthumb-interwork -ffunction-sections -fdata-sections -g -fno-common -fmessage-length=0 -specs=nosys.specs -specs=nano.specs")

SET(CMAKE_CXX_FLAGS_INIT "${COMMON_FLAGS} -std=c++11")
SET(CMAKE_C_FLAGS_INIT "${COMMON_FLAGS} -std=gnu99")
SET(CMAKE_EXE_LINKER_FLAGS_INIT "-Wl,-gc-sections -T ${LINKER_SCRIPT}")

PROJECT(f4-blog C ASM)
set(CMAKE_CXX_STANDARD 11)

#add_definitions(-DARM_MATH_CM4 -DARM_MATH_MATRIX_CHECK -DARM_MATH_ROUNDING -D__FPU_PRESENT=1 )
add_definitions(-D__weak=__attribute__\(\(weak\)\) -D__packed=__attribute__\(\(__packed__\)\) -DUSE_HAL_DRIVER -DSTM32F401xE )

file(GLOB_RECURSE SOURCES "startup/*.*" "Drivers/*.*" "Src/*.*" "Inc/*.*")

include_directories(Inc Drivers/STM32F4xx_HAL_Driver/Inc Drivers/STM32F4xx_HAL_Driver/Inc/Legacy Drivers/CMSIS/Device/ST/STM32F4xx/Include Drivers/CMSIS/Include)

add_executable(${PROJECT_NAME}.elf ${SOURCES} ${LINKER_SCRIPT})

set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-Map=${PROJECT_BINARY_DIR}/${PROJECT_NAME}.map")

set(HEX_FILE ${PROJECT_BINARY_DIR}/${PROJECT_NAME}.hex)
set(BIN_FILE ${PROJECT_BINARY_DIR}/${PROJECT_NAME}.bin)

add_custom_command(TARGET ${PROJECT_NAME}.elf POST_BUILD
        COMMAND ${CMAKE_OBJCOPY} -Oihex $<TARGET_FILE:${PROJECT_NAME}.elf> ${HEX_FILE}
        COMMAND ${CMAKE_OBJCOPY} -Obinary $<TARGET_FILE:${PROJECT_NAME}.elf> ${BIN_FILE}
        COMMENT "Building ${HEX_FILE}
Building ${BIN_FILE}")

add_custom_target(UPLOAD
        arm-none-eabi-gdb -iex "target remote tcp:127.0.0.1:3333"
        -iex "monitor program $<TARGET_FILE:${PROJECT_NAME}.elf>"
        -iex "monitor reset init"
        -iex "disconnect" -iex "quit")
```

## Steps to Reproduce the Problem

  1. Run -> Build
  1. Set Breakpoint.
  1. Run -> Run OCD f4-blog : Firmware Download Success
  1. Run -> Debug OCD f4-blog
![image](https://user-images.githubusercontent.com/9136049/34492296-e9ec45d4-f021-11e7-87d7-866ad7604ba4.png)
![image](https://user-images.githubusercontent.com/9136049/34492088-10c82d0e-f021-11e7-8bf6-d732f4dfd51a.png)

## Specifications

  - Debugger: st-link
  - Board: ST Nuleo F401RE
  - Plugin Version: 1.0.beta1
  - CLion version: 2017.3.1
  - OpenOCD version: 0.10.0
  - GDB Version: GNU gdb (GNU Tools for Arm Embedded Processors 7-2017-q4-major) 8.0.50.20171128-git
  - STM32CubeMX version: 4.23.0
  - Toolchain: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2017-q4-major) 7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204]
  - Platform: OS X Captain 10.11.6 
  - Hardware configuration:

**Comment by elmot** [comment]
Wrong GDB is used. Unfortunately, Mac version of CLion is shipped with single-platform gdb now.
Please uncheck "GDB shipped with CLion" at 1st shown screen and try again.

**Comment by mintisan** [comment]
@elmot It works for me. Thanks.

![image](https://user-images.githubusercontent.com/9136049/34523005-860c21ec-f0d0-11e7-98dd-e39e74931d4b.png)
