### ISSUE TITLE
Feature: Allow to customize "load firmware"

### ISSUE THREAD

**Issue by Niondir** [elmot/clion-embedded-arm#75]
## Expected Behavior

I would like to create a run configuration that does not load the firmware automatically.

In addition it would be nice to have a "reload firmware" button in the OpenOCD console, so I can rebuild my project until it compiles and then just reload the firmware without restarting the debugger.

Just some personal preferences, feel free to discuss it.

**Comment by elmot** [comment]
Actually you can do that already. Run `Tools`->`Run OpenOCD`
then create a run configuration of type `GDB Remote Debug` with remote args `tcp:localhost:3333` and run it.

**Comment by elmot** [comment]
Related to #64
