### ISSUE TITLE
Fix compatibility with CLion 2018.1 EAP

### ISSUE THREAD

**Issue by kiciek** [elmot/clion-embedded-arm#76]
Last compatible CLion is 2017.3.2

**Comment by phaethon** [comment]
Updated CLion this morning to 2018.1 and got "incompatible with this installation" trying to install latest plugin version.

**Comment by elmot** [comment]
I am working on it. Hold on

**Comment by elmot** [comment]
[Version 1.1.alpha](https://github.com/elmot/clion-embedded-arm/releases/tag/1.1.alpha1) works with CLion 2018.1

**Comment by phaethon** [comment]
Thanks a lot! It now works! (at least using a minimal test)
