### ISSUE TITLE
Makefile plugin integration

### ISSUE THREAD

**Issue by belussi** [elmot/clion-embedded-arm#87]
I wonder if it would be possible to integrate or implement cooperation OpneOCD plugin with Makefile plugin: https://victor.kropp.name/projects/makefile/

I have large Makefile project and something like this would be useful if don't want or you can't migrate to Cmake.

**Comment by elmot** [comment]
Duplicate to #91

**Comment by elmot** [comment]
Well, this is not a duplicate, but CLion 2018.1 is going to support Makefile out-of-the-box, hopefully no need to extra plugins.
